### ISSUE TITLE
Bug: Location not recorded for events on Android

### ISSUE THREAD

**Issue by duncancarroll** [happydata/nomie-lab#2]
I have GPS location turned on on my Android phone, and I also have "Record Location on Tap" enabled in nomie, but when I look at the `geo` field in couchdb, it is empty for the events, and the map in nomie-lab defaults to some other location.

**Comment by brandoncorbin** [comment]
Hey Duncan, which version are you running of Nomie? As for things not working in nomie-lab that's not surprising as I haven't spent any time on it since 1.1 dev started. I hope to get back to the Lab once 1.1 is released.

**Comment by duncancarroll** [comment]
Android reports it as 1.0.0, but the app itself reports it as "DEV b2"

**Comment by duncancarroll** [comment]
It looks like it started working now.  I'm not sure why it wasn't working initially since my location was always turned on.  I'll close this for now.  Thanks.

**Comment by brandoncorbin** [comment]
@duncancarroll you should consider updated to the version in the app store too - it will be much more stable and a smoother upgrade for 1.1. Thanks again for your help!

**Comment by duncancarroll** [comment]
@brandoncorbin The Google Play Store lists this as being the latest version--is there a newer version than 1.0.0 in the Play Store?

**Comment by brandoncorbin** [comment]
@duncancarroll no that would be the latest one. Are you still unable to record locations?

**Comment by duncancarroll** [comment]
It's working now thanks!
